/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utilidades.ConfigurationFactory;
import utilidades.ConfigTelas;

/**
 *
 * @author Atendimento
 */
public class TelaConfiguracaoJDialog extends javax.swing.JDialog {

    /**
     * Creates new form TelaConfiguracaoJDialog
     */
    ConfigurationFactory cf;

    public TelaConfiguracaoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ConfigTelas ct = new ConfigTelas(jPanel1, 300, 400);
        ct.carregarConfig(jPanel1);
        try {
            this.cf = new ConfigurationFactory("main");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaConfiguracaoJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTextFieldName.setText(cf.DBNAME);
        jTextFieldHost.setText(cf.DBHOST);
        jTextFieldDataBase.setText(cf.DATABASE);
        jTextFieldPort.setText(String.valueOf(cf.DBPORT));
        jTextFieldUser.setText(cf.DBUSER);
        jPasswordFieldPassword.setText(cf.DBPASSWORD);
        jTextFieldCidade.setText(cf.CIDADE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldResponsavel = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldDocumento = new javax.swing.JTextField();
        jCheckBoxControlaDataImpressao = new javax.swing.JCheckBox();
        jTextFieldChave = new javax.swing.JTextField();
        jCheckBoxControlaHorario = new javax.swing.JCheckBox();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonSalvar1 = new javax.swing.JButton();
        jButtonSair1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldHost = new javax.swing.JTextField();
        jTextFieldDataBase = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jButtonBanco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextFieldResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 54, 277, 20));
        jPanel2.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 85, 277, 20));
        jPanel2.add(jTextFieldDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 116, 277, 20));

        jCheckBoxControlaDataImpressao.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jCheckBoxControlaDataImpressao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 20));
        jPanel2.add(jTextFieldChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 176, 277, 20));

        jCheckBoxControlaHorario.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jCheckBoxControlaHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 209, -1, 20));
        jPanel2.add(jTextFieldCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 147, 277, 20));

        jLabel9.setText("Nome:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, 20));

        jLabel10.setText("Email:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, 20));

        jLabel11.setText("Documento:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, 20));

        jLabel12.setText("Chave de Acesso:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, -1, 20));

        jLabel13.setText("Controla data de Impressão:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 20));

        jLabel15.setText("Controla Horário:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, 20));

        jLabel8.setText("Cidade");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Configurações do Sistema");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 364, -1));

        jButtonSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/salvar.png"))); // NOI18N
        jButtonSalvar1.setMnemonic('a');
        jButtonSalvar1.setText("Salvar");
        jButtonSalvar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalvar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 80, 80));

        jButtonSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/sair.png"))); // NOI18N
        jButtonSair1.setMnemonic('s');
        jButtonSair1.setText("Sair");
        jButtonSair1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSair1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 80, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/senha.png"))); // NOI18N
        jButton1.setText("Gera Chave");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, 80));

        jTabbedPane2.addTab("Sistema", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configurações de acesso ao Banco de Dados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 364, -1));

        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, 20));

        jLabel3.setText("Host");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, 20));

        jLabel4.setText("Database");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, 20));

        jLabel5.setText("User");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, -1, 20));

        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, 20));
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 54, 275, -1));
        jPanel1.add(jTextFieldHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 85, 277, -1));
        jPanel1.add(jTextFieldDataBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 147, 277, -1));
        jPanel1.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 178, 277, -1));

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/sair.png"))); // NOI18N
        jButtonSair.setMnemonic('s');
        jButtonSair.setText("Sair");
        jButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 80, 80));

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/cancelar.png"))); // NOI18N
        jButtonCancelar.setMnemonic('c');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 80));

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/salvar.png"))); // NOI18N
        jButtonSalvar.setMnemonic('a');
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 80, 80));
        jPanel1.add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 209, 277, -1));

        jLabel7.setText("Port:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, 20));
        jPanel1.add(jTextFieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 116, 277, -1));

        jButtonBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/basic_data_32.png"))); // NOI18N
        jButtonBanco.setMnemonic('b');
        jButtonBanco.setText("Banco de Dados");
        jButtonBanco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBanco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBancoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 110, 80));

        jTabbedPane2.addTab("Banco de Dados", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        salvaConfiguracao();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void salvaConfiguracao() {

        cf.DBNAME = jTextFieldName.getText();
        cf.DBHOST = jTextFieldHost.getText();
        cf.DBPORT = jTextFieldPort.getText();
        cf.DATABASE = jTextFieldDataBase.getText();
        cf.DBUSER = jTextFieldUser.getText();
        cf.CIDADE = jTextFieldCidade.getText();
        cf.SERIAL = jTextFieldChave.getText();

        char[] senhaTemp = jPasswordFieldPassword.getPassword();
        String senha = "";
        for (int i = 0; i < senhaTemp.length; i++) {
            senha = senha + senhaTemp[i];
        }
        cf.DBPASSWORD = senha;
        cf.gravaConfiguracao();

    }

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBancoActionPerformed
        new TelaBackupJDialog(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButtonBancoActionPerformed

    private void jButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar1ActionPerformed
        salvaConfiguracao();
    }//GEN-LAST:event_jButtonSalvar1ActionPerformed

    private void jButtonSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSair1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaConfiguracaoJDialog dialog = new TelaConfiguracaoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBanco;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSair1;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JCheckBox jCheckBoxControlaDataImpressao;
    private javax.swing.JCheckBox jCheckBoxControlaHorario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldChave;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldDataBase;
    private javax.swing.JTextField jTextFieldDocumento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldResponsavel;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
