/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.PacienteDAO;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Consulta;
import model.Paciente;
import relatorios.ExecutaRelatorio;
import utilidades.ConfigTelas;
import utilidades.ConnectionFactory;
import utilidades.Datas;

/**
 *
 * @author Nasser
 */
public class TelaConsultasPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaPadrao
     */
    Paciente pac;
    PacienteDAO pDAO;

    public TelaConsultasPaciente(Paciente paciente, Consulta consulta) {
        this.pac = paciente;
        initComponents();
        jComboBoxConsultas.setVisible(false);
        Consulta selecionada = consulta;
        selecionaConsulta(consulta);
        ConfigTelas ct = new ConfigTelas(this);
        ct.carregarConfig(this);
        this.setResizable(true);
    }

    private void selecionaConsulta(Consulta consulta) {
        int index = 0;
        for (int i = 0; i < this.paciente1.getConsultaList().size(); i++) {
            if (this.paciente1.getConsultaList().get(i).equals(consulta)) {
                index = i;
                jTable1.setRowSelectionInterval(index, index);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = ConnectionFactory.getEntityManager();
        paciente1 = pac;
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jComboBoxConsultas = new javax.swing.JComboBox();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSintomas = new javax.swing.JTextArea();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaExames = new javax.swing.JTextArea();
        jButtonRelatorioExame = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaReceita = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaControlado = new javax.swing.JTextArea();
        jButtonRelatorioReceita = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaAtestado = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextAreaLaudo = new javax.swing.JTextArea();
        jButtonRelatorioAtestado = new javax.swing.JButton();
        jButtonRelatorioLaudo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPaciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDataConsulta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldHoraConsulta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonDetalhar = new javax.swing.JButton();

        paciente1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                paciente1PropertyChange(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 990, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/salvar.png"))); // NOI18N
        jButtonSalvar.setMnemonic('A');
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/sair.png"))); // NOI18N
        jButtonSair.setMnemonic('S');
        jButtonSair.setText("Sair");
        jButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jComboBoxConsultas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${consultaList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, paciente1, eLProperty, jComboBoxConsultas);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), jComboBoxConsultas, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/agenda_adiciona.png"))); // NOI18N
        jButtonNovo.setMnemonic('N');
        jButtonNovo.setText("Novo");
        jButtonNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/cancelar.png"))); // NOI18N
        jButtonCancelar.setMnemonic('C');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243)
                .addComponent(jComboBoxConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar)
                    .addComponent(jComboBoxConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonSair)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 579, -1, -1));

        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${consultaList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, paciente1, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sDataConsulta}"));
        columnBinding.setColumnName("Data");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sHoraConsulta}"));
        columnBinding.setColumnName("Hora");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idtipoConsulta.descricao}"));
        columnBinding.setColumnName("Tipoconsulta");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, 247, 502));

        jTextAreaSintomas.setColumns(20);
        jTextAreaSintomas.setLineWrap(true);
        jTextAreaSintomas.setRows(5);
        jTextAreaSintomas.setWrapStyleWord(true);
        jTextAreaSintomas.setBorder(javax.swing.BorderFactory.createTitledBorder("Sintomas"));
        jTextAreaSintomas.setMaximumSize(new java.awt.Dimension(116, 43));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.sintomas}"), jTextAreaSintomas, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jTextAreaSintomas, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane3.setViewportView(jTextAreaSintomas);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane3.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Sintomas", new javax.swing.ImageIcon(getClass().getResource("/icones32/status_32.png")), jLayeredPane3); // NOI18N

        jTextAreaExames.setColumns(20);
        jTextAreaExames.setLineWrap(true);
        jTextAreaExames.setRows(5);
        jTextAreaExames.setWrapStyleWord(true);
        jTextAreaExames.setBorder(javax.swing.BorderFactory.createTitledBorder("Exames"));
        jTextAreaExames.setMaximumSize(new java.awt.Dimension(116, 43));
        jTextAreaExames.setMinimumSize(new java.awt.Dimension(116, 43));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.exames}"), jTextAreaExames, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jTextAreaExames, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane4.setViewportView(jTextAreaExames);

        jButtonRelatorioExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/impressora_32.png"))); // NOI18N
        jButtonRelatorioExame.setMnemonic('I');
        jButtonRelatorioExame.setText("Imprimir");
        jButtonRelatorioExame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelatorioExame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRelatorioExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioExameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRelatorioExame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jButtonRelatorioExame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane4.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jButtonRelatorioExame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Exames", new javax.swing.ImageIcon(getClass().getResource("/icones32/exame2.png")), jLayeredPane4); // NOI18N

        jTextAreaReceita.setColumns(20);
        jTextAreaReceita.setLineWrap(true);
        jTextAreaReceita.setRows(5);
        jTextAreaReceita.setWrapStyleWord(true);
        jTextAreaReceita.setBorder(javax.swing.BorderFactory.createTitledBorder("Receita"));
        jTextAreaReceita.setMaximumSize(new java.awt.Dimension(116, 43));
        jTextAreaReceita.setMinimumSize(new java.awt.Dimension(116, 43));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.receita}"), jTextAreaReceita, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jTextAreaReceita, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane5.setViewportView(jTextAreaReceita);

        jTextAreaControlado.setColumns(20);
        jTextAreaControlado.setLineWrap(true);
        jTextAreaControlado.setRows(5);
        jTextAreaControlado.setWrapStyleWord(true);
        jTextAreaControlado.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicação Controlada"));
        jTextAreaControlado.setMaximumSize(new java.awt.Dimension(116, 43));
        jTextAreaControlado.setMinimumSize(new java.awt.Dimension(116, 43));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.medicacao}"), jTextAreaControlado, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jTextAreaControlado, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane6.setViewportView(jTextAreaControlado);

        jButtonRelatorioReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/impressora_32.png"))); // NOI18N
        jButtonRelatorioReceita.setMnemonic('I');
        jButtonRelatorioReceita.setText("Imprimir");
        jButtonRelatorioReceita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelatorioReceita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRelatorioReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRelatorioReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButtonRelatorioReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonRelatorioReceita, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Medicação", new javax.swing.ImageIcon(getClass().getResource("/icones32/medicamento.png")), jLayeredPane1); // NOI18N

        jTextAreaAtestado.setColumns(20);
        jTextAreaAtestado.setLineWrap(true);
        jTextAreaAtestado.setRows(5);
        jTextAreaAtestado.setWrapStyleWord(true);
        jTextAreaAtestado.setBorder(javax.swing.BorderFactory.createTitledBorder("Atestado"));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.atestado}"), jTextAreaAtestado, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jTextAreaAtestado, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane8.setViewportView(jTextAreaAtestado);

        jTextAreaLaudo.setColumns(20);
        jTextAreaLaudo.setLineWrap(true);
        jTextAreaLaudo.setRows(5);
        jTextAreaLaudo.setWrapStyleWord(true);
        jTextAreaLaudo.setBorder(javax.swing.BorderFactory.createTitledBorder("Laudo"));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.laudo}"), jTextAreaLaudo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jTextAreaLaudo, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane10.setViewportView(jTextAreaLaudo);

        jButtonRelatorioAtestado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/receita_imprimir.png"))); // NOI18N
        jButtonRelatorioAtestado.setMnemonic('I');
        jButtonRelatorioAtestado.setText("Imprimir");
        jButtonRelatorioAtestado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelatorioAtestado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRelatorioAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioAtestadoActionPerformed(evt);
            }
        });

        jButtonRelatorioLaudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones32/receita_imprimir.png"))); // NOI18N
        jButtonRelatorioLaudo.setMnemonic('I');
        jButtonRelatorioLaudo.setText("Imprimir");
        jButtonRelatorioLaudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelatorioLaudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRelatorioLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioLaudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(jScrollPane10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRelatorioLaudo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRelatorioAtestado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRelatorioAtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRelatorioLaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jLayeredPane2.setLayer(jScrollPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButtonRelatorioAtestado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButtonRelatorioLaudo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Atestado/Laudo", new javax.swing.ImageIcon(getClass().getResource("/icones32/exame.png")), jLayeredPane2); // NOI18N

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 108, -1, 453));

        jLabel13.setText("Paciente");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 65, 360, -1));

        jTextFieldPaciente.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, paciente1, org.jdesktop.beansbinding.ELProperty.create("${nome}"), jTextFieldPaciente, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 360, -1));

        jLabel11.setText("Data");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 65, 100, -1));

        jTextFieldDataConsulta.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.sDataConsulta}"), jTextFieldDataConsulta, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldDataConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 100, -1));

        jLabel12.setText("Hora");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 65, 108, -1));

        jTextFieldHoraConsulta.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxConsultas, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.sHoraConsulta}"), jTextFieldHoraConsulta, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextFieldHoraConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 108, -1));

        jLabel2.setText("Consultas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 229, -1));

        jLabel3.setText("Idade");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 65, 58, -1));

        jTextField1.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, paciente1, org.jdesktop.beansbinding.ELProperty.create("${idade}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 60, -1));

        jButtonDetalhar.setMnemonic('d');
        jButtonDetalhar.setText("Detalhar");
        jButtonDetalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalharActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDetalhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 79, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRelatorioExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioExameActionPerformed
        if (jComboBoxConsultas.getSelectedIndex() != -1) {
            this.atualizaPaciente(false);
            Consulta c = (Consulta) jComboBoxConsultas.getSelectedItem();
            if (c.getExames() != null) {
                Date data = Datas.getCurrentTime();
                new TelaSelecionaData(this, true).setVisible(true);
                data = TelaSelecionaData.getData();
                ExecutaRelatorio er = new ExecutaRelatorio();
                er.abrirRelatorioReceita(c, "Exames", c.getExames(), data);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Campo exame está vazio");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma consulta");
        }
    }//GEN-LAST:event_jButtonRelatorioExameActionPerformed

    private void jButtonRelatorioReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioReceitaActionPerformed

        if (jComboBoxConsultas.getSelectedIndex() != -1) {
            this.atualizaPaciente(false);
            Consulta c = (Consulta) jComboBoxConsultas.getSelectedItem();
            if (c.getReceita() != null) {
                Date data = Datas.getCurrentTime();
                new TelaSelecionaData(this, true).setVisible(true);
                data = TelaSelecionaData.getData();
                
                ExecutaRelatorio er = new ExecutaRelatorio();
                er.abrirRelatorioReceita(c, "Receita", c.getReceita(), data);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Campo receita está vazio");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma consulta");
        }
    }//GEN-LAST:event_jButtonRelatorioReceitaActionPerformed

    private void jButtonRelatorioAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioAtestadoActionPerformed
        if (jComboBoxConsultas.getSelectedIndex() != -1) {
            this.atualizaPaciente(false);
            Consulta c = (Consulta) jComboBoxConsultas.getSelectedItem();
            if (c.getAtestado() != null) {
                Date data = Datas.getCurrentTime();
                new TelaSelecionaData(this, true).setVisible(true);
                data = TelaSelecionaData.getData();
                
                ExecutaRelatorio er = new ExecutaRelatorio();
                er.abrirRelatorioReceita(c, "Atestado", c.getAtestado(), data);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Campo atestado está vazio");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma consulta");
        }
    }//GEN-LAST:event_jButtonRelatorioAtestadoActionPerformed

    private void jButtonRelatorioLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioLaudoActionPerformed
        if (jComboBoxConsultas.getSelectedIndex() != -1) {
            this.atualizaPaciente(false);
            Consulta c = (Consulta) jComboBoxConsultas.getSelectedItem();
            if (c.getLaudo() != null) {
                Date data = Datas.getCurrentTime();
                new TelaSelecionaData(this, true).setVisible(true);
                data = TelaSelecionaData.getData();
                
                ExecutaRelatorio er = new ExecutaRelatorio();
                er.abrirRelatorioReceita(c, "Laudo", c.getLaudo(), data);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Campo laudo está vazio");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma consulta");
        }
    }//GEN-LAST:event_jButtonRelatorioLaudoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        atualizaPaciente(true);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void atualizaPaciente(boolean mensagem) {
        pDAO = new PacienteDAO();
        pDAO.atualizaConsultaPaciente(this.paciente1);

    }
    private void jButtonDetalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalharActionPerformed
        new TelaCadastroPacienteJDialog(this, true, paciente1, false, true).setVisible(true);
    }//GEN-LAST:event_jButtonDetalharActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        new TelaCadastroConsulta(paciente1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        entityManager.refresh(paciente1);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void paciente1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_paciente1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultasPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultasPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultasPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultasPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaConsultasPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDetalhar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonRelatorioAtestado;
    private javax.swing.JButton jButtonRelatorioExame;
    private javax.swing.JButton jButtonRelatorioLaudo;
    private javax.swing.JButton jButtonRelatorioReceita;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaAtestado;
    private javax.swing.JTextArea jTextAreaControlado;
    private javax.swing.JTextArea jTextAreaExames;
    private javax.swing.JTextArea jTextAreaLaudo;
    private javax.swing.JTextArea jTextAreaReceita;
    private javax.swing.JTextArea jTextAreaSintomas;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldDataConsulta;
    private javax.swing.JTextField jTextFieldHoraConsulta;
    private javax.swing.JTextField jTextFieldPaciente;
    private model.Paciente paciente1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
